### ISSUE TITLE
AoT build error

### ISSUE THREAD

**Issue by zoamel** [NetanelBasal/angular2-take-until-destroy#8]
When I try to build app with usage of AoT using Angular 5 and Angular CLI 1.5 I'm getting this error from `angular2-take-until-destroy`:
`ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js`

From what I understand it may the problem of incorrect import from rxjs in library.

**Comment by NetanelBasal** [comment]
I did not check the library with Angular 5 yet. I will investigate soon. Thanks.

**Comment by NetanelBasal** [comment]
I just published version 2.0.0, check it, please. You should import the lib like this:
`{ TakeUntilDestroy }`

**Comment by zoamel** [comment]
Working perfectly now, thank you :)I think this issue can be closed
